version: "3"
services:
  gobarberdb:
    container_name: gobarberdb
    image: postgres
    environment:
      POSTGRES_PASSWORD: gobarber
      POSTGRES_USER: gobarber
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  gobarberdbadmin:
    container_name: gobarberdbadmin
    image: dpage/pgadmin4:4.15
    environment:
      PGADMIN_DEFAULT_EMAIL: gobarber@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: gobarber
    ports:
      - "5050:80"
    depends_on:
      - gobarberdb
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
      - ./volumes/config_local.py:/pgadmin

  mongo:
    container_name: mongo
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mongo
    #   MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    links:
      - mongo

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"